grafana:
  grafana.ini:
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
  enabled: true
  namespaceOverride: ""
  adminPassword: novacodedemo

  service:
    type: NodePort
    nodePort: 30870

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'vllm'
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/vllm

  dashboardsConfigMaps:
    vllm: "vllm-dashboard"

  sidecar:
    dashboards:
      annotations:
        grafana_folder: "Kubernetes"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true
      searchNamespace: monitoring

  persistence:
    enabled: true
    existingClaim: novacode-shared-pvc
    accessModes:
      - ReadWriteMany
    size: 1Ti
    type: pvc
    subPath: grafana

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'vllm-llama'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - inference
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: vllm-llama;http
      - job_name: 'vllm-mistral'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - inference
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: vllm-mistral;http
