apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: lora-train-job
spec:
  entrypoint: "/home/ray/app/train.sh" # IF this directory is read only, it will likely fail
  runtimeEnvYAML: |
    env_vars:
      MLFLOW_TRACKING_URI: "file:////home/ray/app/mlflow"
      NUMEXPR_MAX_THREADS: "64"
      CUDA_VISIBLE_DEVICES: "2,3,4,5,6,7"
  shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished: 120000
  clusterSelector:
    ray.io/cluster: "llama-3-8b-raycluster-wt28n" # MUST BE SET MANUALLY TODAY BASED ON THE CLUSTER NAME; JUST THE SUFFIX, then rerun just ./kubernetes/finetune-llm/submit.sh
