apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: lora-train-job
spec:
  entrypoint: "/home/ray/app/train.sh" # IF this directory is read only, it will likely fail
  runtimeEnvYAML: |
    env_vars:
      MLFLOW_TRACKING_URI: "file:///tmp/mlflow/mlflow"
      NUMEXPR_MAX_THREADS: "64"
      PYTORCH_NO_CUDA_MEMORY_CACHING: "1"
      TENSOR_PARALLELISM: "2"
      PIPELINE_PARALLELISM: "1"
  shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished: 120000
  clusterSelector:
    ray.io/cluster: "raycluster-llm-finetuning"
