apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: lora-train-job
spec:
  entrypoint: "bash -c 'cp -r /home/ray/app/. /tmp/ && cd /tmp && bash /tmp/train.sh'"
  runtimeEnvYAML: |
    env_vars:
      WANDB_DISABLED: "true"
      COMET_MODE: "disabled"
      MLFLOW_TRACKING_URI: "file:///tmp/mlflow"
      NUMEXPR_MAX_THREADS: "64"
  shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished: 120000
  clusterSelector:
    ray.io/cluster: "llama-3-8b-raycluster-dgbsc"
