apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: lora-train-job
spec:
  entrypoint: "cp -r /home/ray/app/. /tmp/ && bash /tmp/train.sh"
  runtimeEnvYAML: |
    pip:
      - "-r /home/ray/app/requirements.txt"
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 120
  clusterSelector:
    # This must match the metadata.name of the RayCluster created by the RayService.
    ray.io/cluster: "llama-3-8b-raycluster-98n92"
