apiVersion: v1
kind: Service
metadata:
  name: ray-dashboard
  namespace: default
spec:
  type: NodePort
  selector:
    ray.io/node-type: head
  ports:
    - name: dashboard
      port: 8265
      targetPort: 8265
      nodePort: 30865
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ray-serve
  namespace: default
spec:
  type: NodePort
  selector:
    ray.io/node-type: head
  ports:
    - name: dashboard
      port: 8000
      targetPort: 8000
      nodePort: 30866
      protocol: TCP
---
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama-3-8b
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 8
          num_gpus: 4
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        env_vars:
          CUDA_VISIBLE_DEVICES: "0,1,2,3"
          MODEL_ID: "meta-llama/Llama-3.2-1B-Instruct"
          TENSOR_PARALLELISM: "4"
          PIPELINE_PARALLELISM: "1"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
          - name: ray-head
            image: registry.gitlab.com/deepsense.ai/g-crusoe/crusoe-novacode/ray-ml-vllm:0.6.1.post2
            resources:
              limits:
                cpu: "8"
                memory: "8Gi"
                nvidia.com/gpu: 1
              requests:
                cpu: "8"
                memory: "8Gi"
                nvidia.com/gpu: 1
            env:
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
          imagePullSecrets:
          - name: gitlab-registry
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 0
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: llm
            image: registry.gitlab.com/deepsense.ai/g-crusoe/crusoe-novacode/ray-ml-vllm:0.6.1.post2
            resources:
              limits:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: 4
              requests:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: 4
            env:
            - name: CUDA_VISIBLE_DEVICES
              value: "0,1,2,3"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
          imagePullSecrets:
          - name: gitlab-registry