---
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama-3-8b
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path: ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: "64"
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        env_vars:
          MODEL_ID: "meta-llama/Llama-3.2-1B-Instruct"
          TENSOR_PARALLELISM: "2"
          PIPELINE_PARALLELISM: "1"
  rayClusterConfig:
    headGroupSpec:
      serviceType: NodePort
      rayStartParams:
        dashboard-host: "0.0.0.0"
        num-gpus: "8"
      template:
        spec:
          containers:
          - name: ray-head
            image: registry.gitlab.com/deepsense.ai/g-crusoe/crusoe-novacode/ray-ml-vllm:0.6.1.post2
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 44217
              name: as-metrics
            - containerPort: 44227
              name: dash-metrics
            - containerPort: 8000
              name: serve
            resources:
              limits:
                cpu: "64"
                memory: "200Gi"
                nvidia.com/gpu: "8"
              requests:
                cpu: "64"
                memory: "200Gi"
                nvidia.com/gpu: "8"
            env:
            - name: RAY_GRAFANA_IFRAME_HOST
              value: http://204.52.26.113:30870
            - name: RAY_GRAFANA_HOST
              value: http://prometheus-grafana.prometheus-system.svc:80
            - name: RAY_PROMETHEUS_HOST
              value: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc:9090
            - name: NUMEXPR_MAX_THREADS
              value: "64"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
          imagePullSecrets:
          - name: gitlab-registry
    workerGroupSpecs: [] # Not Today