grafana:
  grafana.ini:
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
  enabled: true
  namespaceOverride: ""
  adminPassword: admin

  service:
    type: NodePort
    nodePort: 30870

  sidecar:
    dashboards:
      annotations:
        grafana_folder: "Kubernetes"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true

  persistence:
    enabled: true
    existingClaim: novacode-shared-pvc
    accessModes:
      - ReadWriteMany
    size: 1Ti
    type: pvc
    subPath: grafana

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'vllm-inference'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: vllm-inference-service;http
      - job_name: 'vllm-inference-finetuned'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: vllm-inference-service-finetuned;http
