apiVersion: v1
kind: Service
metadata:
  name: vllm-inference-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: vllm-inference
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
      protocol: TCP
