apiVersion: v1
kind: PersistentVolume
metadata:
  name: nova-cluster-model-disk
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crusoe-static
  csi:
    driver: ssd.csi.crusoe.ai
    volumeHandle: $DISK_ID_PLACEHOLDER # "939e6a3f-c286-4f69-83ad-7527fa31714c"
    volumeAttributes:
      csi.crusoe.ai/serial-number: $DISK_SERIAL_NUMBER_PLACEHOLDER # "3ECBAFCDD8D49DC0196"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east1-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store
spec:
  storageClassName: crusoe-static
  volumeName: nova-cluster-model-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
