image:
  repository: rayproject/ray-ml
  tag: latest-py311-gpu

worker:
  resources:
    limits:
      nvidia.com/gpu: 1
      cpu: "1"
      memory: "1G"
    requests:
      nvidia.com/gpu: 1
      cpu: "1"
      memory: "1G"
