apiVersion: v1
kind: Service
metadata:
  name: vllm-llama
  namespace: inference
spec:
  type: ClusterIP
  selector:
    app: vllm-llama
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
