kind: PersistentVolume
apiVersion: v1
metadata:
  name: novacode-shared-pv-inference
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: crusoe-csi-driver-ssd-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fs.csi.crusoe.ai
    readOnly: false
    volumeHandle: ${VOLUME_HANDLE}
    volumeAttributes:
      csi.crusoe.ai/serial-number: ${SERIAL_NUMBER}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - ${REGION}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: novacode-shared-pv-monitoring
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: crusoe-csi-driver-ssd-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fs.csi.crusoe.ai
    readOnly: false
    volumeHandle: ${VOLUME_HANDLE}
    volumeAttributes:
      csi.crusoe.ai/serial-number: ${SERIAL_NUMBER}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - ${REGION}
