apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novacode-shared-pvc
  namespace: inference
spec:
  storageClassName: crusoe-csi-driver-ssd-sc
  volumeName: novacode-shared-pv-inference
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novacode-shared-pvc
  namespace: monitoring
spec:
  storageClassName: crusoe-csi-driver-ssd-sc
  volumeName: novacode-shared-pv-monitoring
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
