apiVersion: v1
kind: Service
metadata:
  name: vllm-mistral
  namespace: inference
spec:
  type: ClusterIP
  selector:
    app: vllm-mistral
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
